apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZV1JwYkhsaGN6cG5hSEJmUzI4MGRrNDJha2RvYzFOck0zRm9ORTVWWWxsbVZXTTNRbk5JVURCaU1uSTFkblZIIn19fQ==
type: kubernetes.io/dockerconfigjson
